export const Locations = [
    { value: 'Academic City',label: 'Academic City' },
    { value: 'Akoya Oxygen', label: 'Akoya Oxygen' },
    { value: 'Al Awir', label: 'Al Awir' },
    { value: 'Al Badaa', label: 'Al Badaa' },
    { value: 'Al Barari', label: 'Al Barari'  },
    { value: 'Al Barsha', label: 'Al Barsha'  },
    { value: 'Al Furjan', label: 'Al Furjan'  },
    { value: 'Al Hudaiba', label: 'Al Hudaiba'  },
    { value: 'Al Jafiliya', label: 'Al Jafiliya'  },
    { value: 'Al Karama', label: 'Al Karama'  },
    { value: 'Al Khawaneej', label: 'Al Khawaneej'  },
    { value: 'Al Mamzar', label: 'Al Mamzar'  },
    { value: 'Al Manara', label: 'Al Manara'  },
    { value: 'Al Mina', label: 'Al Mina'  },
    { value: 'Al Mizhar', label: 'Al Mizhar'  },
    { value: 'Al Nahda', label: 'Al Nahda'  },
    { value: 'Al Quoz', label: 'Al Quoz'  },
    { value: 'Al Qusais', label: 'Al Qusais'  },
    { value: 'Al Rashidiya', label: 'Al Rashidiya'  },
    { value: 'Al Safa', label: 'Al Safa'  },
    { value: 'Al Satwa', label: 'Al Satwa'  },
    { value: 'Al Sufouh', label: 'Al Sufouh'  },
    { value: 'Al Twar', label: 'Al Twar'  },
    { value: 'Al Warqaa', label: 'Al Warqaa'  },
    { value: 'Al Warsan', label: 'Al Warsan'  },
    { value: 'Al Wasl', label: 'Al Wasl'  },
    { value: 'Arabian Ranches', label: 'Arabian Ranches'  },
    { value: 'Arabian Ranches 2', label: 'Arabian Ranches 2'  },
    { value: 'Arjan', label: 'Arjan'  },
    { value: 'Barsha Heights', label: 'Barsha Heights'  },
    { value: 'Bluewaters Island', label: 'Bluewaters Island'  },
    { value: 'Bukadra', label: 'Bukadra'  },
    { value: 'Bur Dubai', label: 'Bur Dubai'  },
    { value: 'Business Bay', label: 'Business Bay'  },
    { value: 'Culture Village', label: 'Culture Village'  },
    { value: 'DAMAC Hills', label: 'DAMAC Hills'  },
    { value: 'DIFC', label: 'DIFC'  },
    { value: 'Deira', label: 'Deira'  },
    { value: 'Discovery Gardens', label: 'Discovery Gardens'  },
    { value: 'Downtown Dubai', label: 'Downtown Dubai'  },
    { value: 'Downtown Jebel Ali', label: 'Downtown Jebel Ali'  },
    { value: 'Dubai Festival City', label: 'Dubai Festival City'  },
    { value: 'Dubai Hills Estate', label: 'Dubai Hills Estate'  },
    { value: 'Dubai Industrial Park', label: 'Dubai Industrial Park'  },
    { value: 'Dubai Internet City', label: 'Dubai Internet City'  },
    { value: 'Dubai Investment Park', label: 'Dubai Investment Park'  },
    { value: 'Dubai Marina', label: 'Dubai Marina'  },
    { value: 'Dubai Media City', label: 'Dubai Media City'  },
    { value: 'Dubai Production City', label: 'Dubai Production City'  },
    { value: 'Dubai Residence Complex', label: 'Dubai Residence Complex'  },
    { value: 'Dubai Science Park', label: 'Dubai Science Park'  },
    { value: 'Dubai Silicon Oasis', label: 'Dubai Silicon Oasis'  },
    { value: 'Dubai South', label: 'Dubai South'  },
    { value: 'Dubai Sports City', label: 'Dubai Sports City'  },
    { value: 'Dubai Studio City', label: 'Dubai Studio City'  },
    { value: 'Dubai Waterfront', label: 'Dubai Waterfront'  },
    { value: 'Dubai World Central', label: 'Dubai World Central'  },
    { value: 'Dubailand', label: 'Dubailand'  },
    { value: 'Emirates Hills', label: 'Emirates Hills'  },
    { value: 'Green Community', label: 'Green Community'  },
    { value: 'International City', label: ''  },
    { value: 'Jebel Ali', label: 'Jebel Ali'  },
    { value: 'Jumeirah', label: 'Jumeirah'  },
    { value: 'Jumeirah Beach Residence', label: 'Jumeirah Beach Residence'  },
    { value: 'Jumeirah Golf Estate', label: 'Jumeirah Golf Estate'  },
    { value: 'Jumeirah Heights', label: 'Jumeirah Heights'  },
    { value: 'Jumeirah Islands', label: 'Jumeirah Islands'  },
    { value: 'Jumeirah Lake Towers', label: 'Jumeirah Lake Towers'  },
    { value: 'Jumeirah Park', label: 'Jumeirah Park'  },
    { value: 'Jumeirah Village Circle', label: 'Jumeirah Village Circle'  },
    { value: 'Jumeirah Village Triangle', label: 'Jumeirah Village Triangle'  },
    { value: 'Liwan', label: 'Liwan'  },
    { value: 'Meydan City', label: 'Meydan City'  },
    { value: 'Mirdif', label: 'Mirdif'  },
    { value: 'Mohammad Bin Rashid City', label: 'Mohammad Bin Rashid City' },
    { value: 'Motor City', label: 'Motor City'  },
    { value: 'Mudon', label: 'Mudon'  },
    { value: 'Muhaisnah', label: 'Muhaisnah'  },
    { value: 'Nad Al Hamar', label: 'Nad Al Hamar'  },
    { value: 'Nad Al Sheba', label: 'Nad Al Sheba'  },
    { value: 'Old Town', label: 'Old Town'  },
    { value: 'Oud Al Muteena', label: 'Oud Al Muteena'  },
    { value: 'Palm Jumeirah', label: 'Palm Jumeirah'  },
    { value: 'Ras Al Khor', label: 'Ras Al Khor'  },
    { value: 'Reem', label: 'Reem'  },
    { value: 'Remraam', label: 'Remraam'  },
    { value: 'Serena', label: 'Serena'  },
    { value: 'Sheikh Zayed Road', label: 'Sheikh Zayed Road'  },
    { value: 'The Gardens', label: 'The Gardens'  },
    { value: 'The Greens' , label: 'The Greens' },
    { value: 'The Hills' , label: 'The Hills' },
    { value: 'The Lagoons' , label: 'The Lagoons' },
    { value: 'The Lakes' , label: 'The Lakes' },
    { value: 'The Meadows' , label: 'The Meadows' },
    { value: 'The Springs' , label: 'The Springs' },
    { value: 'The Sustainable City' , label: 'The Sustainable City' },
    { value: 'The Views' , label: 'The Views' },
    { value: 'The Villa' , label: 'The Villa' },
    { value: 'Town Square' , label: 'Town Square' },
    { value: 'Umm Al Sheif' , label: 'Umm Al Sheif' },
    { value: 'Umm Ramool' , label: 'Umm Ramool' },
    { value: 'Umm Suqeim' , label: 'Umm Suqeim' },
    { value: 'Wadi Al Safa 2' , label: 'Wadi Al Safa 2' },
    { value: 'Wasl Gate' , label: 'Wasl Gate' },
    { value: 'World Trade Centre' , label: 'World Trade Centre' }
];